### ISSUE TITLE
import { Explore } from 'components' not working but with './components';

### ISSUE THREAD

**Issue by SheikhG1900** [xkawi/react-universal-saga-modular#7] opened 2017-02-18 18:30 UTC
I think i am missing something related to webpack. A lot of "import" requires to prepend './'.
please help.

**Comment by xkawi** [comment] 2017-02-19 00:24
@SheikhG1900 How your file structure looks like? And from which file that you are trying import that component?

If you modified the webpack config, sharing it might help.

**Comment by xkawi** [comment] 2017-02-19 00:28
@SheikhG1900 If you modified src/components/index.js file, can post the modifed code? Because sometime, I also encounter that but mostly due to the index.js file not exporting the components correctly.

**Comment by abdulwahid-360training** [comment] 2017-03-24 08:02
I didn't modify anything. I just tried to run it by following instructions given in Readme file. Exception is throwing at following location.
https://github.com/xkawi/react-universal-saga-modular/blob/8d74e6bc3b9985552c558725aca3cac0221474c4/src/containers/App/App.js#L4.

Same code is written in **react-universal-saga** project. It is working fine there. Really strange :(
https://github.com/xkawi/react-universal-saga/blob/ab49f28b4cb772ee19b59b9fd2a74ccc950dc624/src/containers/App/App.js#L4

**Comment by xkawi** [comment] 2017-06-07 09:36
closing this for now, as can't replicate or at least need more information. feel free to open it again if it's not resolved yet.

**Closed as completed by xkawi** 2017-06-07 09:36 UTC

**Comment by devlinsmith** [comment] 2017-09-20 08:53
I am also having this issue. I have not modified the webpack scripts, or the default seed module structure or imports. The issue is not present when running as admin, but that is not an option for a hosted solution. I have ensured the user running the process has full access rights to the directory, even after running build and run seperately. This was reproduced on 2 individual ubuntu 16.04 LTS EC2 boxes hosted on Amazon. Issue doesn't occur in my local development environment.
